set_property SRC_FILE_INFO {cfile:C:/Users/smgandhi/Downloads/Tutorial_Inverter-20210916T223857Z-001/Tutorial_Inverter/Tutorial_Inverter/Tutorial/LearnVHDL/LearnVHDL.srcs/constrs_1/imports/labmanuals/Zybo-Z7-Master.xdc rfile:../../../LearnVHDL.srcs/constrs_1/imports/labmanuals/Zybo-Z7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G15   IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L19N_T3_VREF_35 Sch=sw[0]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports { B }]
