encode:
	python3 ws1.encode.py

ws1:
	python3 ws1.dump.tree.1.py
	@echo "******************"
	python3 ws1.load.tree.1.py
	python3 ws1.load.tree.1.v2.py

pl:
	python3 pickle.load.v1.py

pd:
	python3 pickle.dump.v1.py

w:
	python3 ws1.huffman.py

h:
	python3 huffman.py
