webtalk_init -webtalk_dir /home/dekr0/Code/XilinxProject/lab_2_sequence_detector/Lab_2_seq_detecor.sim/sim_1/behav/xsim/xsim.dir/seq_fsm_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Oct 15 23:54:45 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7915a367-8d42-48de-a702-3f6d7b797511" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a10cd7d1fec54118b4db1e1849ee47ab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4199.928 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114660_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1707244834 -regid "" -xml /home/dekr0/Code/XilinxProject/lab_2_sequence_detector/Lab_2_seq_detecor.sim/sim_1/behav/xsim/xsim.dir/seq_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/dekr0/Code/XilinxProject/lab_2_sequence_detector/Lab_2_seq_detecor.sim/sim_1/behav/xsim/xsim.dir/seq_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/dekr0/Code/XilinxProject/lab_2_sequence_detector/Lab_2_seq_detecor.sim/sim_1/behav/xsim/xsim.dir/seq_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
