compile:
	g++ -c first.cpp second.cpp  # compile first.cpp and second.cpp into two separete object files
	g++ first.o second.o  # link two object files together and create an executable file (default a.out)
