webtalk_init -webtalk_dir /home/dekr0/Code/XilinxProject/Lab_2_seq_detecor/Lab_2_seq_detecor.sim/sim_1/behav/xsim/xsim.dir/seq_fsm_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  5 17:36:12 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fc02955f-be93-4ee3-bc9f-2976f02d1fbc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a10cd7d1fec54118b4db1e1849ee47ab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2600.012 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114648_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2342300495 -regid "" -xml /home/dekr0/Code/XilinxProject/Lab_2_seq_detecor/Lab_2_seq_detecor.sim/sim_1/behav/xsim/xsim.dir/seq_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/dekr0/Code/XilinxProject/Lab_2_seq_detecor/Lab_2_seq_detecor.sim/sim_1/behav/xsim/xsim.dir/seq_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/dekr0/Code/XilinxProject/Lab_2_seq_detecor/Lab_2_seq_detecor.sim/sim_1/behav/xsim/xsim.dir/seq_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
