compile:
	g++ -o leaders leaders.cpp
extreme:
	python3 etest/make_test.py
	./leaders < etest/test.txt
extreme-:
	./leaders < etest/t1.txt
	./leaders < etest/t2.txt
	./leaders < etest/t3.txt
	./leaders < etest/t4.txt
	./leaders < etest/t5.txt
	./leaders < etest/t6.txt
	./leaders < etest/t7.txt
test:
	./leaders < ntest/001-stdin.txt > nout/t1.txt
	./leaders < ntest/002-stdin.txt > nout/t2.txt
	./leaders < ntest/003-stdin.txt > nout/t3.txt
	./leaders < ntest/004-stdin.txt > nout/t4.txt
	./leaders < ntest/005-stdin.txt > nout/t5.txt

