#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 28 22:00:33 MDT 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 2da8c7d8ba4a4a32ac21c2ee7aa2d32e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot priority_encoder_7_3_tb_behav xil_defaultlib.priority_encoder_7_3_tb -log elaborate.log"
xelab -wto 2da8c7d8ba4a4a32ac21c2ee7aa2d32e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot priority_encoder_7_3_tb_behav xil_defaultlib.priority_encoder_7_3_tb -log elaborate.log

